// Module code: CS5003
// Module: Masters Programming Projects
// Creating an Emojitar Generator

// Get the emojitar components from the CSV file
// The data from the CSV file was converted to JSON in a CSV converter
const emojitars = [
  {
    type: "face",
    id: " face-yellow",
    description: "Basic emoji face",
    filename: "face-yellow.png",
    user: " system",
    date: "",
  },
  {
    type: "face",
    id: " face-grey",
    description: "Grey emoji face",
    filename: "face-grey.png",
    user: " system",
    date: "",
  },
  {
    type: "face",
    id: " face-pink-rosy",
    description: "Pink emoji face with rosy cheeks",
    filename: "face-pink-rosy.png",
    user: " system",
    date: "",
  },
  {
    type: "hair",
    id: " hair-bob-brown",
    description: "Brown bob",
    filename: "hair-bob-brown.png",
    user: " system",
    date: "",
  },
  {
    type: "hair",
    id: " hair-bowl-brown",
    description: "Brown short cut",
    filename: "hair-bowl-brown.png",
    user: " system",
    date: "",
  },
  {
    type: "hair",
    id: " hair-curly-brown",
    description: "Mid-length brown curly hair",
    filename: "hair-curly-brown.png",
    user: " system",
    date: "",
  },
  {
    type: "hair",
    id: " hair-curly-ginger",
    description: "Mid-length ginger curly hair",
    filename: "hair-curly-ginger.png",
    user: " system",
    date: "",
  },
  {
    type: "hair",
    id: " hair-pigtails-brown",
    description: "Short brown pigtails",
    filename: "hair-pigtails-brown.png",
    user: " system",
    date: "",
  },
  {
    type: "hair",
    id: " hair-short-brown",
    description: "Short brown curly hair",
    filename: "hair-short-brown.png",
    user: " system",
    date: "",
  },
  {
    type: "hair",
    id: " hair-short-teal",
    description: "Short teal curly hair",
    filename: "hair-short-teal.png",
    user: " system)",
    date: "",
  },
  {
    type: "eyes",
    id: " eyes-smiley",
    description: "Smiley eyes",
    filename: "eyes-smiley.png",
    user: " system",
    date: "",
  },
  {
    type: "eyes",
    id: " eyes",
    description: "Oval eyes",
    filename: "eyes.png",
    user: " system",
    date: "",
  },
  {
    type: "eyes",
    id: " eyes-smiley-pale",
    description: "Pale smiley eyes",
    filename: "eyes-smiley-pale-blue.png",
    user: " system",
    date: "",
  },
  {
    type: "eyes",
    id: " eyes-pale",
    description: "Pale oval eyes",
    filename: "eyes-pale-blue.png",
    user: " system",
    date: "",
  },
  {
    type: "mouth",
    id: " mouth-grin",
    description: "Teethy grin",
    filename: "mouth-grin.png",
    user: " system",
    date: "",
  },
  {
    type: "mouth",
    id: " mouth-grin-pink",
    description: "Pink-lipped teethy grin",
    filename: "mouth-grin-pink.png",
    user: " system",
    date: "",
  },
  {
    type: "mouth",
    id: " mouth-smile",
    description: "Basic emoji smile",
    filename: "mouth-smile.png",
    user: " system",
    date: "",
  },
];

module.exports = { emojitars };
